### ISSUE TITLE
Naming issue

### ISSUE THREAD

**Issue by cyian-1756** [Zylann/godot_opensimplex#1]
This doesn't compile unless you remove the godot_ from the name. It's the same issue godot_voxel had

**Comment by Zylann** [comment]
I really don't like this fact... I want to name the repo the way I want, mostly to organize my Github :/
Anyways, that's a minor annoyance if you just specify the folder:

```
git clone https://github.com/Zylann/godot_opensimplex.git opensimplex
```

**Comment by cyian-1756** [comment]
Yup it sucks but I figured I'd point it out so you could put a footnote in the read me or something about it

**Comment by Zylann** [comment]
Done :)
