### ISSUE TITLE
Compile Error with Godot 3 master

### ISSUE THREAD

**Issue by HummusSamurai** [Zylann/godot_opensimplex#2]
I get the following error when compiling opensimplex with Godot 3 master, both when compiling with with the voxel module and alone.

> In file included from modules/opensimplex/register_types.cpp:2:0:
> modules/opensimplex/noise.h:10:33: error: ISO C++ forbids declaration of 'OBJ_TYPE' with no type [-fpermissive]
>      OBJ_TYPE(OsnNoise, Reference)
>                                  ^
> 

Full pastebin of the errors: https://pastebin.com/HNXFSxwM

Googling the issue led me to this: https://github.com/khairul169/gdsqlite/issues/8
And so I am thinking it could be a problem on your end?

Thank you and I hope I can get your modules to work! They seem amazing!

**Comment by Xrayez** [comment]
I have recently made changes to this module on my local machine to compile it with Godot 3 master. I can try to make a pull request.

**Comment by HummusSamurai** [comment]
@Xrayez I am looking forward to it! And will test it directly when you do.

**Comment by Zylann** [comment]
Aaah yeah the module uses an outdated API, Godot 3 changed fast these last months.
It needs to use GDCLASS and not have type hints in registration. Maybe more.
