### ISSUE TITLE
I made it work with GD Native

### ISSUE THREAD

**Issue by MartiniMoe** [Zylann/godot_opensimplex#4]
Hi Zylann,

I made your library work with GD Native! Im not a C++ Developer and had to hack around a little, but it works now. I was wondering if you plan to port this to GD Native and if you would be interested in how I did this? If so I would clean it up a little and put it into a seperate repo.

**Comment by Zylann** [comment]
I have a port work in progress, but I was stuck on the part where I need to pass an instance of OsnNoise to OsnFractalNoise. For some reason the instance I passed was converted into a shallow class with all fields uninitialized, which crashed on null pointers. So I stopped working on it waiting for a fix: https://github.com/godotengine/godot/issues/8490
Maybe it was fixed now? Did you try this test case?

**Comment by MartiniMoe** [comment]
Thats great to hear!
I had the exact same problem and talked to karroffel (creator of GD Native) about this. At the moment its not possible to pass references like this in GD Native :(
Theres an open issue about it here: https://github.com/godotengine/godot/issues/8490

I worked around it by instantiating OsnNoise inside OsnFractalNoise and adding set_seed() and get_seed() methods to OsnFractalNoise :/ Ugly, but does the job for now...

// Edit: Just saw that issue is opened by you m) haha
// You linked it... its too early for me, sorry :D Unfortunately its not fixed yet, but karroffel said he would have some time to work on GD Native in the near future and probably fix it.

**Comment by Zylann** [comment]
Gah... I was about to investigate again but you did it before me then. Thanks for that :)
Constructing OsnNoise within OsnFractalNoise is ugly indeed, not only because you can't re-use the same noise source, but also because OsnNoise allocates a significant amount of memory (around the size of an 256x256 image) to store its permutations per seed, which I didn't like when you compare that the FastNoise library, which doesn't allocate any memory. So I came up with this referencing which is actually quite good because it can serve as a base to compose noises.
I hope this gets fixed soon^^"

**Comment by LunaSquee** [comment]
What's the progress on this?

**Comment by Zylann** [comment]
@LunaSquee GDNative is improving, Ref<T> works better. We can nearly send custom objects as arguments but I still have some problems with it (https://github.com/GodotNativeTools/godot-cpp/issues/91). Otherwise it's possible to implement just Noise with internal fractal noise, like @MartiniMoe said.

**Comment by scayze** [comment]
Whats the status of this? would love to see this on gdnative :D

**Comment by Zylann** [comment]
I'm not working on this at the moment. If someone can make a GDNative version of it that would be most likely in another repo than this one.

**Comment by Xrayez** [comment]
The module is no longer maintained: https://github.com/Zylann/godot_opensimplex/commit/f8b93c4fb6766413d7c5f0fc4170388e532055e1, the issue can be closed I guess.
