### ISSUE TITLE
Create tag/branch for godot 2.x users

### ISSUE THREAD

**Issue by rakai93** [Zylann/godot_opensimplex#5]
Hi,

first of all: I really appreciate this module as it helps a lot when working with dynamic maps.
However, I had trouble compiling godot 2.x with your master state until I noticed that the commit porting it to version 3 alpha was already merged.

What do you think about creating a tag or branch at commit becacba so that godot 2.x users have an easy time seing what is going on?

**Comment by Zylann** [comment]
I just created a godot2 branch

**Comment by rakai93** [comment]
Thank!
