### ISSUE TITLE
Inegrate opensimplex into godot core

### ISSUE THREAD

**Issue by JFonS** [Zylann/godot_opensimplex#6]
I want to work on intergating opensimplex into godot itself and exposing it as a new type of Texture resource. I was thinkinig on taking your module  as a base and change whatever is needed to create the new resource type. Are you ok with that?

**Comment by Zylann** [comment]
I'm ok with that, this module is just barely exposing the lib with a few fractal function helpers which would be too slow if used in GDScript.

Are you going to expose the noise generator as well? Will it be able to generate images with a given format or only textures?

**Comment by JFonS** [comment]
The idea is to allow using it as a texture and also directly from GDscript. 

I'm not sure about the image part, I will probably just implement textures and if I see there's a need for images I can add it later.

**Comment by radishes** [comment]
Would love this, and I second Zylann's comment - exposing the `OSNoise` noise generator gdscript functions is what I specifically would find extremely useful.

**Comment by JFonS** [comment]
@radishes Well, last time I asked @reduz he seemd to be fine with it and @Zylann's implementation already works so you can most likely expect OSNoise in Godot 3.1

**Comment by Zylann** [comment]
> I'm not sure about the image part, I will probably just implement textures and if I see there's a need for images I can add it later.

Well, the thing is, if you want it to work for textures, you have to generate an image anyways before uploading it (this is not a GPU implementation :p), so to me it makes sense to expose generation to `Image`. You can still do it in GDScript but it's going to be slower.

Also, just one thing to know about the library itself:
It allocates a bunch of memory when you choose the seed. That sounds "fine", but on the other hand I looked at another lib (`FastNoise`) which did not allocate anything. Just so you are aware :)

**Comment by JFonS** [comment]
@Zylann  Adding a method to Image would be more invasive than just adding a module that can be disabled if not needed.

I can add a method to OSNoise that returns a noise Image, but I'm not sure if there's any use for it.

**Comment by Zylann** [comment]
I never said to add it to `Image` though. The reason why I suggest to generate to an Image is because `Image` is the only *native* grid data structure we can use in GDScript, and games can use it for gameplay purpose rather than visual (one reason why `Image` importer was added). If one wants to quickly generate a procedural heightmap in game with this method, they have to upload the texture, then download it back to create the collider, which is silly. But I guess that this upcoming `NoiseTexture` is primarily intented for materials, so people will still have to iterate images manually in GDScript if they want another purpose.

**Comment by JFonS** [comment]
Fair enough :)

**Comment by Xrayez** [comment]
@JFonS if what you want is actually be able to generate nice visual textures (even seamless ones), take a look at my [ANL module](https://github.com/Xrayez/godot-anl) which is a wrapper over [Accidental Noise Library](https://github.com/JTippetts/accidental-noise-library). which I think is more general-purpose noise generator (though slower than any other noise generator implementations). I'd be glad to help. Though there might be legal implications regarding simplex noise, but not sure about that.

**Comment by JFonS** [comment]
@Xrayez I think Simplex is a no-go since it is patent protected. I don't plan to work for too long on noise textures in godot. My main goal is to add the basics so that we at least have something and let someone else improve on that if they fee like it.

**Comment by JFonS** [comment]
My final PR on the godot repo:
https://github.com/godotengine/godot/pull/21569

Closing this issue :)
